.TH r-go-led 1 "2020-12-04" "r-go-tools-led"
.\" --------------------------------------------------------------------
.SH NAME
r-go-led \- control the special LED on R-Go Tools keyboards
.\" --------------------------------------------------------------------
.SH SYNOPSIS
\fBr-go-led\fP [\fB\-r\fP|\fB\-g\fP|\fB\-y\fP]
[\fB\-v\fP \fIvendorID\fP]
[\fB\-p\fP \fIproductID\fP]
.\" --------------------------------------------------------------------
.SH DESCRIPTION
This program controls the special \(lqR\(rq LED on R-Go Tools keyboards.
.\" --------------------------------------------------------------------
.SH OPTIONS
When invoked without arguments, the LED will be turned \fBoff\fP.
.TP
\fB\-r\fP, \fB\-g\fP, \fB\-y\fP
Set the LED to red, green, or yellow.
.TP
\fB\-v\fP \fIvendorID\fP, \fB\-p\fP \fIproductID\fP
All \fI/dev/hidraw*\fP files that match these USB IDs will be operated
on. These arguments default to a \fIvendorID\fP of \fB0911\fP and a
\fIproductID\fP of \fB2188\fP.
.\" --------------------------------------------------------------------
.SH PERMISSIONS
In order to send USB commands to the device, the program needs access to
the corresponding hidraw file (one of \fI/dev/hidraw*\fP). The easiest
way to accomplish this is to install a \fBsudo\fP(8) rule.
.P
Another option is to create a new system group for this purpose. You can
then use a \fBudev\fP(7) rule to grant access:
.P
\f(CW
.nf
KERNEL=="hidraw*", \\
    ATTRS{idVendor}=="0911", ATTRS{idProduct}=="2188", \\
    GROUP="rgoled"
.fi
\fP
.P
Now, you can install the \fBr-go-led\fP binary as group \(lqrgoled\(rq
and set the SGID bit.
.\" --------------------------------------------------------------------
.SH LICENSE
\fBr-go-led\fP is released under the MIT license. See the accompanying
\fILICENSE\fP file.
.\" --------------------------------------------------------------------
.SH HISTORY
\fBr-go-led\fP was originally written by Peter Hofmann. The project
was started in November 2020.
.\" --------------------------------------------------------------------
.SH "SEE ALSO"
.BR r-go-break-reminder (1).
