.TH r-go-break-reminder 1 "2020-12-14" "r-go-tools-led"
.\" --------------------------------------------------------------------
.SH NAME
r-go-break-reminder \- light up the LED on R-Go Tools keyboards after long streaks of typing
.\" --------------------------------------------------------------------
.SH SYNOPSIS
\fBr-go-break-reminder\fP
[\fB\-i\fP \fImin_idle\fP]
[\fB\-w\fP \fImax_work\fP]
[\fB\-s\fP]
[\fB\-v\fP \fIvendorID\fP]
[\fB\-p\fP \fIproductID\fP]
.\" --------------------------------------------------------------------
.SH DESCRIPTION
\fBr-go-break-reminder\fP alerts you on long streaks of user activity
using the special \(lqR\(rq LED on R-Go Tools keyboards.
.\" --------------------------------------------------------------------
.SH OPTIONS
.TP
\fB\-i\fP \fImin_idle\fP, \fB\-w\fP \fImax_work\fP
After using the computer for \fImax_work\fP seconds, the LED will be
turned on (red), until you made a break for at least \fImin_idle\fP
seconds (green LED).
.TP
\fB\-s\fP
Call \fBr-go-led\fP using \fBsudo\fP(8).
.TP
\fB\-v\fP \fIvendorID\fP, \fB\-p\fP \fIproductID\fP
Both these options will be passed to \fBr-go-led\fP to determine which
device to control.
.\" --------------------------------------------------------------------
.SH LICENSE
\fBr-go-break-reminder\fP is released under the MIT license. See the
accompanying \fILICENSE\fP file.
.\" --------------------------------------------------------------------
.SH HISTORY
\fBr-go-break-reminder\fP was originally written by Peter Hofmann,
inspired by what the author read about the original R-Go Tools software.
The project was started in November 2020.
.\" --------------------------------------------------------------------
.SH "SEE ALSO"
.BR r-go-led (1),
.BR xprintidle (1).
