#!/bin/sh

[ -n "$DEBUG" ] && set -x
set -e

max_work_duration_s=$((30 * 60))
min_idle_duration_s=$((5 * 50))
sudo=

while getopts i:w:S name
do
    case "$name" in
        i) min_idle_duration_s=$OPTARG ;;
        w) max_work_duration_s=$OPTARG ;;
        S) sudo=sudo ;;
    esac
done

last_good_idle=$(date +%s)

while sleep 15
do
    now=$(date +%s)
    now_idle=$(xprintidle)
    if [ $((now_idle / 1000)) -ge "$min_idle_duration_s" ]
    then
        last_good_idle=$now
    fi

    if [ $((now - last_good_idle)) -ge "$max_work_duration_s" ]
    then
        $sudo r-go-led -r
    else
        $sudo r-go-led
    fi
done
